HEX

FE2000000 CONSTANT GPIO_BASE
GPIO_BASE 04 + CONSTANT GPFSEL1
GPIO_BASE 1C + CONSTANT GPSET0
GPIO_BASE 28 + CONSTANT GPCLR0

: MASK ( pos -- ) 1 SWAP LSHIFT ;

: GPIO_OUT ( pin --) MASK ;
: GPIO_IN ( pin -- ) ;



