
BASEADDR 200000 + CONSTANT GPIO_BASE

\STRUTTURA PER DEFINIRE INDIRIZZI MULTIPLI
: GPIO{ GPIO_BASE 34 + ;   
: }GPIO DROP ;
GPIO{
PIN GPLEV0 PIN GPLEV1 SKIP
PIN GPEDS0 PIN GPEDS1 SKIP
PIN GPREN0 PIN GPREN1 SKIP
PIN GPFEN0 PIN GPFEN1 SKIP
PIN GPHEN0 PIN GPHEN1 SKIP
PIN GPLEN0 PIN GPLEN1
}GPIO

GPIO_BASE 00 + CONSTANT GPFSEL0
\GPIO_BASE 04 + CONSTANT GPFSEL1
\GPIO_BASE 1C + CONSTANT GPSET0
\GPIO_BASE 28 + CONSTANT GPCLR0
\GPIO_BASE 4C + CONSTANT GPREN0
\GPIO_BASE 58 + CONSTANT GPFEN0
\GPIO_BASE E4 + CONSTANT GPPUP0

: GPON ( pin -- ) 20 /MOD 4 * BASEADDR 20001C + + SWAP MASK SWAP ! ;

: GPOFF ( pin -- ) 20 /MOD 4 * BASEADDR 200028 + + SWAP MASK SWAP ! ;

: GPFSEL ( gpioPinNumber -- addr_gpfsel clr_value_gpfsel offset_base )
    A /MOD 4 * GPIO_BASE + SWAP 3 * DUP 7 SWAP LSHIFT ROT DUP @ ROT INVERT AND ROT ;
: GPIO_INPUT ( addr_gpfsel clr_value_gpfsel offset_base -- )
    1 SWAP LSHIFT INVERT AND SWAP ! ;
: GPIO_OUTPUT ( addr_gpfsel clr_value_gpfsel offset_base -- )
    1 SWAP LSHIFT OR SWAP ! ;
: GPIO_AF0 ( addr_gpfsel clr_value_gpfsel offset_base -- )
    1 SWAP 2 + LSHIFT OR SWAP ! ;
: EVENT_DETECT ( pin -- event )
    MASK GPEDS0 @ AND 0 <> -1 = ;
: PIN_LEVEL ( pin -- level )
    MASK GPLEV0 @ AND 0 = IF 0 ELSE 1 THEN ;
: CLEAR_EVENT ( pin -- )
    MASK GPEDS0 @ OR GPEDS0 ! ;
: FALLING_EDGE_DETECT_ENABLE ( pin -- )
    MASK GPFEN0 @ OR GPFEN0 ! ;

: READ GPFEN0 @ ;
: READ2 GPREN0 @ ;
\ SETUP DEI PIN GPIO 2 & 3 PER I2C (ALT FUNCTIONS)
\: SETUP 900 GPFSEL0 @ OR GPFSEL0 ! ;

\ DI BASE I RESISTORI PULL UP SONO GIA' IMPOSTATI PER I PIN GPIO 2 & 3
\ HEX (4AA95555) TO BIN (0100 1010 1010 1001 0101 0101 0101 0101)
\ OGNI DUE BIT SI MODIFICA LA CONFIGURAZIONE DI UN PIN
\: SETPUP 4AA95555 GPPUP0 ! ;

\ FALLING EDGE DETECT ENABLE PER IL PIN SPECIFICATO
\: FEN (n -- ) MASK GPFEN0 ! ;

\ RISING EDGE DETECT ENABLE PER IL PIN SPECIFICATO
\: REN (n -- ) MASK GPAREN0 ! ;
